module.exports = {
  ollamaHost: process.env.OLLAMA_HOST || 'http://localhost:11434',
  hardware: {
    tag: 'p40',
    gpu: 'Tesla P40 24GB',
    vramTotal: 24,
  },
  candidates: [
    'qwen3.6:latest',
    'qwen3.6:27b',
    'qwen3.5:27b',
    'qwen3.5:9b',
    'gemma4:26b',
    'phi4-reasoning:plus',
	'gemma4:31b',
	'devstral-small-2',
	'deepseek-r1:14b',
	'deepseek-r1:32b',
	'deepseek-coder-v2:16b',
  ],
  jurors: [
    'gemma4:26b',
    'phi4-reasoning:plus',
    'qwen3.6:27b',
    'qwen3.5:9b',
  ],
  capabilities: ['coding', 'reasoning', 'structured', 'summary', 'adversarial', 'archaeology', 'synthesis'],
  weights: {
    correctness: 8,
    instruction_following: 4,
    format_compliance: 4,
    conciseness: 2,
  },
  scenarioWeights: {
    coding: 2, reasoning: 2, structured: 2, summary: 2, adversarial: 1, archaeology: 2, synthesis: 2,
  },
  resultsDir: './results',
  capabilitiesDir: './capabilities',
  candidateTemp: 0.7,
  judgeTemp: 0.1,
  chatTimeoutMs: 1221 * 1000,
  maxJudgeResponseChars: 6000,
  serverPort: 3773,
}
